/*
                _  __                             _
               | |/ /                            | |
               | ' / ___  ___ _ __ ___  _   _  __| |
               |  < / _ \/ __| '_ ` _ \| | | |/ _` |
               | . \ (_) \__ \ | | | | | |_| | (_| |
               |_|\_\___/|___/_| |_| |_|\__,_|\__,_|

                     Server program entry point
*/

import { REPORT } from "../Shared/Log/REPORT";
import { Syslog } from "../Shared/Log/Syslog";
import { HttpsServer } from "../Server/Net/HttpsServer";
import { Game } from "../Server/Game/Game";
import { Engine } from "../Server/Engine/Engine";

export const timeOfBoot = new Date();

// Include sourcemap support module. It uses .js.map files generated by
// typecript compiler to change stack traces to actually show TypeScript
// stack trace (instead of stack trace in generated JavaScript).
import * as SourceMapSupport from "source-map-support";
SourceMapSupport.install();

function stop()
{
  Syslog.log("[INFO]", `Kosmud server has stopped normally.`);
}

async function start()
{
  Syslog.log("[INFO]", `Starting Kosmud server...`);

  try
  {
    await HttpsServer.startServers();
    await Game.load();
    /// Tohle si tu nechám kvůli budoucí teminologii. Na klientu
    /// by to mělo bejt stejně.
    // await Game.init();
  }
  catch (error)
  {
    REPORT(error, "Failed to start");
    return;
  }

  await Engine.loop();

  stop();
}

// tslint:disable-next-line:no-floating-promises
start();