"use strict";
/*
                _  __                             _
               | |/ /                            | |
               | ' / ___  ___ _ __ ___  _   _  __| |
               |  < / _ \/ __| '_ ` _ \| | | |/ _` |
               | . \ (_) \__ \ | | | | | |_| | (_| |
               |_|\_\___/|___/_| |_| |_|\__,_|\__,_|


                     Server program entry point
*/
Object.defineProperty(exports, "__esModule", { value: true });
// Include sourcemap support module. It uses .js.map files generated by
// typecript compiler to change stack traces to actually show TypeScript
// stack trace (instead of stack trace in generated JavaScript).
require('source-map-support').install();
// Include package.json file (located in Kosmud directory)
// (In case you were wondering, we need to get all the way up from
//  '/Server/js/Server' because the require() is done in runtime.)
let packageDotJson = require('../../../package.json');
const Server_1 = require("../Server/Application/Server");
Server_1.Server.start(packageDotJson.name, packageDotJson.version);
//# sourceMappingURL=KosmudServer.js.map